### ISSUE TITLE
关于Virtual Local Space的问题

### ISSUE THREAD

**Issue by loserhou** [dop0/DVPE#3]
请问生成各自视角的PE后，为什么要统一旋转到Virtual Local Space，最后再旋转回来，这样有什么好处吗？

**Comment by loserhou** [comment]
不旋转到Virtual Local Space，最后直接预测不可以吗？

**Comment by dop0** [comment]
都旋转到虚拟局部空间之后，才会在这个坐标系下生成各自PE，目的是为了解耦相机位姿，使得模型不需要从世界坐标系下环视的PE来得到目标位置信息，从更小的区域PE得到位置信息明显更容易，更有利于模型训练。

**Comment by loserhou** [comment]
> 都旋转到虚拟局部空间之后，才会在这个坐标系下生成各自PE，目的是为了解耦相机位姿，使得模型不需要从世界坐标系下环视的PE来得到目标位置信息，从更小的区域PE得到位置信息明显更容易，更有利于模型训练。

谢谢解答，还有一个问题希望您解答
<img width="511" alt="709ebb032d432be03d49ec0d60068fe" src="https://github.com/user-attachments/assets/ecfb0111-7f3e-4d1f-8dfe-ffe3121bdc5e">
这里我看预测了像素位置和对应深度，是怎么转换到世界坐标系的，有公式提到过程吗，为什么没有像素位置乘深度这个步骤再转换到世界坐标系？耽误您的时间了！

**Comment by dop0** [comment]
不好意思回复晚了，这个部分我们参考了论文 Lifting any 2D Object Detector to 3D Detection，论文中公式2-4提到了具体变换过程。另外，在`torch.inverse(roi_intrinsics) @ roi_reference_points.unsqueeze(-1)` 这一步前，应该将像素位置乘深度，这里我们实现有错误，感谢你指出，后续有机会会修改并验证效果。

**Comment by loserhou** [comment]
> 不好意思回复晚了，这个部分我们参考了论文 Lifting any 2D Object Detector to 3D Detection，论文中公式2-4提到了具体变换过程。另外，在`torch.inverse(roi_intrinsics) @ roi_reference_points.unsqueeze(-1)` 这一步前，应该将像素位置乘深度，这里我们实现有错误，感谢你指出，后续有机会会修改并验证效果。

感谢回复，我修改后验证一下，看看是否会涨点哈哈哈
