### ISSUE TITLE
您好，请问可以发我一份vovnet训练的config吗？

### ISSUE THREAD

**Issue by loserhou** [dop0/DVPE#6]

**Comment by loserhou** [comment]
load_from = 'ckpts/dd3d_det_final.pth'
revise_keys = [('backbone', 'img_backbone')]
需要这样加载vovnet权重吗？为什么在streampetr上不需要加revise_keys呢？

**Comment by dop0** [comment]
直接load_from就可以，不用revise_keys。

**Comment by loserhou** [comment]
是的，但是直接运行会报错，修改train文件已解决，谢谢






| |
侯业飞
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月10日 00:34 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
State ***@***.***> |
| 主题 | Re: [dop0/DVPE] 您好，请问可以发我一份vovnet训练的config吗？ (Issue #6) |

直接load_from就可以，不用revise_keys。
